### ISSUE TITLE
Create demo

### ISSUE THREAD

**Issue by vitali-yanushchyk-valor** [unicef/hope-dedup-engine#46]
Develop a demo application to be run locally using Docker Compose. The setup must include all necessary containers for the application to function correctly.
Ensure access to the admin panel at http://localhost:8000/ and provide Swagger documentation for the API. Prepare the database and storage systems, ensuring the existence of DNN files.
Utilize open-source images and DNN files for demonstration purposes.

**Comment by domdinicola** [comment]
can you add a description here @vitali-yanushchyk-valor
